---
apiVersion: v1
kind: Secret
metadata:
  name: orc8r-controller
  labels:
    app.kubernetes.io/component: controller
{{ include "magma-fullstack-upstream.labels" . | indent 4 }}
type: Opaque
data:
  postgres.connstr: {{ printf "dbname=%s user=%s password=%s host=%s port=%d sslmode=disable" .Values.postgresql.database .Values.postgresql.username .Values.postgresql.password .Values.postgresql.name 5432 | b64enc | quote }}
