{{- if .Values.secrets.create }}
{{- $domain := .Values.global.domainName -}}
{{- $existingCerts := lookup "v1" "Secret" .Release.Namespace .Values.secrets.certsName -}}
{{- $ca := genCA (printf "rootca.%s" $domain) (int .Values.secrets.caDays) -}}
{{- $certifierCA := genCA (printf "certifier.%s" $domain) (int .Values.secrets.caDays) -}}
{{- $controller := genSignedCert (printf "controller.%s" $domain) nil (list (printf "*.nms.%s" $domain) (printf "api.%s" $domain) (printf "controller.%s" $domain) (printf "bootstrapper-controller.%s" $domain)) (int .Values.secrets.certDays) $ca -}}
{{- $admin := genSignedCert "admin_operator" nil nil (int .Values.secrets.certDays) $certifierCA -}}
{{- $fluentd := genSignedCert (printf "fluentd.%s" $domain) nil nil (int .Values.secrets.certDays) $certifierCA -}}
{{- $nms := genSignedCert (printf "*.nms.%s" $domain) nil (list (printf "*.nms.%s" $domain)) (int .Values.secrets.certDays) $ca -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.certsName }}
  labels:
{{ include "magma-fullstack-upstream.labels" . | indent 4 }}
type: Opaque
{{- if and .Values.secrets.reuseExisting $existingCerts }}
data:
{{- range $key, $value := $existingCerts.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- else }}
stringData:
  rootCA.pem: |
{{ $ca.Cert | indent 4 }}
  controller.crt: |
{{ $controller.Cert | indent 4 }}
  controller.key: |
{{ $controller.Key | indent 4 }}
  admin_operator.pem: |
{{ $admin.Cert | indent 4 }}
  admin_operator.key.pem: |
{{ $admin.Key | indent 4 }}
  certifier.pem: |
{{ $certifierCA.Cert | indent 4 }}
  certifier.key: |
{{ $certifierCA.Key | indent 4 }}
  vpn_ca.crt: |
{{ $ca.Cert | indent 4 }}
  vpn_ca.key: |
{{ $ca.Key | indent 4 }}
  fluentd.pem: |
{{ $fluentd.Cert | indent 4 }}
  fluentd.key: |
{{ $fluentd.Key | indent 4 }}
  nms_nginx.pem: |
{{ $nms.Cert | indent 4 }}
  nms_nginx.key.pem: |
{{ $nms.Key | indent 4 }}
  bootstrapper.key: |
{{ $ca.Key | indent 4 }}
{{- end }}
--- 
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.envdirName }}
  labels:
{{ include "magma-fullstack-upstream.labels" . | indent 4 }}
type: Opaque
stringData:
  SERVICE_REGISTRY_MODE: k8s
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.configsName }}
  labels:
{{ include "magma-fullstack-upstream.labels" . | indent 4 }}
type: Opaque
stringData:
  elastic.yml: |
    elasticHost: "elasticsearch-master"
    elasticPort: 9200
  analytics.yml: |
    analysisSchedule: 3
{{- end }}
