apiVersion: v1
kind: Service
metadata:
  name: {{ include "ntn.fullname" . }}-mongodb
spec:
  selector: { app.kubernetes.io/instance: {{ .Release.Name }}, app.kubernetes.io/component: mongodb }
  ports: [{ name: mongodb, port: 27017, targetPort: 27017 }]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ntn.fullname" . }}-mongodb
spec:
  replicas: 1
  selector:
    matchLabels: { app.kubernetes.io/instance: {{ .Release.Name }}, app.kubernetes.io/component: mongodb }
  template:
    metadata:
      labels: { app.kubernetes.io/instance: {{ .Release.Name }}, app.kubernetes.io/component: mongodb }
    spec:
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: mongodb
          image: {{ .Values.image.mongodb }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["--bind_ip_all"]
          readinessProbe: { tcpSocket: { port: 27017 }, initialDelaySeconds: 3, periodSeconds: 3 }
