{{/*
Copyright 2020 The Magma Authors.

This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree.

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}
{{- define "agwc.deployment.tpl" -}}
{{ include "magma-agw-upstream.assertNoLatest" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agwc
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: agwc
{{ include "agw-instance-label" . | indent 4 }}
{{ include "default-labels" . | indent 4 }}
{{ include "image-version-label" . | indent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: agwc
{{ include "default-selector-labels" . | indent 6 }}
{{ include "image-version-label" . | indent 6 }}
  template:
    metadata:
      annotations:
        checksum/gateway-config: {{ include (print $.Template.BasePath "/gateway-config.config.yaml") . | sha256sum }}
        checksum/control-proxy-config: {{ include (print $.Template.BasePath "/control-proxy.config.yaml") . | sha256sum }}
        checksum/agw-identity: {{ include (print $.Template.BasePath "/agw-identity.config.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/component: agwc
{{ include "agw-instance-label" . | indent 8 }}
{{ include "default-selector-labels" . | indent 8 }}
{{ include "image-version-label" . | indent 8 }}
    spec:
      restartPolicy: Always
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- if and .Values.orc8r.hostAliases.enabled .Values.orc8r.hostAliases.ip }}
      hostAliases:
        - ip: {{ .Values.orc8r.hostAliases.ip | quote }}
          hostnames:
{{ toYaml .Values.orc8r.hostAliases.hostnames | indent 12 }}
      {{- end }}
      {{- include "agw.podAntiAffinity" . | nindent 6 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      volumes:
        - name: magma-config
          configMap:
            name: gateway-config
        - name: controlproxy-config
          configMap:
            name: controlproxy-config
        - name: agwc-claim
          persistentVolumeClaim:
            claimName: {{ .Values.persistent.name }}
        - name: snowflake-file
          {{- if .Values.gatewayIdentity.snowflake }}
          configMap:
            name: agw-identity
          {{- else }}
          hostPath:
            path: /etc/snowflake
            type: FileOrCreate
          {{- end }}
      containers:
      -
{{ include "agwc.container.tpl" . | indent 8 }}
{{- end -}}
{{- define "agwc.deployment" -}}
{{- include "agwc.util.merge" (append . "agwc.deployment.tpl") -}}
{{- end -}}
