{{- if .Values.secret.create }}
{{- $ca := genCA (printf "%s-agw-ca" .Release.Name) 3650 }}
{{- $gateway := genSignedCert (printf "%s-gateway" .Release.Name) nil (list "gateway" "localhost") 3650 $ca }}
{{- $controller := genSignedCert (printf "%s-controller" .Release.Name) nil (list "controller" "localhost") 3650 $ca }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.certs }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "default-labels" . | indent 4 }}
type: Opaque
data:
  rootCA.pem: {{ $ca.Cert | b64enc | quote }}
  gateway.crt: {{ $gateway.Cert | b64enc | quote }}
  gateway.key: {{ $gateway.Key | b64enc | quote }}
  controller.crt: {{ $controller.Cert | b64enc | quote }}
  controller.key: {{ $controller.Key | b64enc | quote }}
{{- end }}
