{{/*
Adds the upstream Docker Compose liagentd service that is missing from the
experimental upstream agwc Helm chart.
*/}}
{{- if .Values.services.liagentd.enabled }}
---
{{ include "agwc.deployment" (list . "liagentd.deployment") -}}
{{- end }}
{{- define "liagentd.deployment" -}}
metadata:
  labels:
    app.kubernetes.io/component: liagentd
  name: liagentd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: liagentd
  template:
    metadata:
      labels:
        app.kubernetes.io/component: liagentd
    spec:
      containers:
      -
{{ include "agwc.container" (list . "liagentd.container")}}
{{- end -}}
{{- define "liagentd.container" -}}
name: liagentd
args:
  - /usr/local/bin/liagentd
image: "{{ .Values.image.repository }}/agw_gateway_c{{ .Values.image.arch }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
{{- end -}}
