# Build with herlesupreeth/docker_open5gs commit
# 7464234a9f79718df1836d24d688be745a5272d1 as the Docker build context.
ARG BASE_IMAGE=docker-open5gs-kamailio-base:7464234
FROM ${BASE_IMAGE}

COPY icscf /mnt/icscf
COPY scscf /mnt/scscf
COPY pcscf /mnt/pcscf
