# SPDX-License-Identifier: LicenseRef-CSSL-1.0
uicc0 = {
imsi = "{{ .Values.subscriber.imsi }}";
key = "{{ .Values.subscriber.key }}";
opc = "{{ .Values.subscriber.opc }}";
pdu_sessions = ({ dnn = "{{ .Values.subscriber.dnn }}"; nssai_sst = {{ .Values.subscriber.sst }}; });
}
position0 = {
    x = 0.0;
    y = 0.0;
    z = 6377900.0;
}
rfsimulator = (
{
    serveraddr = "{{ .Values.addresses.gnbRf }}";
  serverport = 4043;
  options = ();
  prop_delay = 238.74;
}
);
