{{- if not .Values.orc8r.nmsAdmin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "magma-ebpf.nmsSecretName" . }}
  labels:
    {{- include "magma-ebpf.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.orc8r.nmsAdmin.emailKey }}: {{ .Values.orc8r.nmsAdmin.email | quote }}
  {{ .Values.orc8r.nmsAdmin.passwordKey }}: {{ .Values.orc8r.nmsAdmin.password | quote }}
{{- end }}
