{{- if and .Values.orc8r.rootCA.pem (not .Values.orc8r.rootCA.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "magma-ebpf.rootCASecretName" . }}
  labels:
    {{- include "magma-ebpf.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.orc8r.rootCA.secretKey }}: |
{{ .Values.orc8r.rootCA.pem | nindent 4 }}
{{- end }}
