{{- range $name, $config := .Values.interfaces }}
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ueransim-{{ $name }}
  labels:
    {{- include "ueransim.selectorLabels" $ | nindent 4 }}
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "{{ $config.master }}",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "{{ $config.subnet }}",
        "range_start": "{{ $config.rangeStart }}",
        "range_end": "{{ $config.rangeEnd }}"
      },
      "capabilities": {"mac": true}
    }
{{- end }}
