apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ueransim.name" . }}-gnb
  labels:
    {{- include "ueransim.selectorLabels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ueransim.name" . }}-gnb
  labels:
    {{- include "ueransim.selectorLabels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ueransim.name" . }}-gnb
  labels:
    {{- include "ueransim.selectorLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ueransim.name" . }}-gnb
subjects:
  - kind: ServiceAccount
    name: {{ include "ueransim.name" . }}-gnb
