{{- range $name, $network := .Values.multus }}
{{- $type := default $.Values.multusDefaults.type $network.type }}
{{- $master := default $.Values.multusDefaults.master $network.master }}
{{- $mode := default $.Values.multusDefaults.mode $network.mode }}
{{- $ipamType := dig "ipam" "type" $.Values.multusDefaults.ipam.type $network }}
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: {{ include "open5gs-4g.fullname" $ }}-{{ $name }}
  labels:
    {{- include "open5gs-4g.labels" $ | nindent 4 }}
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "{{ include "open5gs-4g.fullname" $ }}-{{ $name }}",
      "type": "{{ $type }}",
      {{- if eq $type "bridge" }}
      "bridge": "{{ include "open5gs-4g.fullname" $ | trunc 7 }}-{{ replace "-" "" $name | trunc 6 }}",
      {{- else if or (eq $type "macvlan") (eq $type "ipvlan") }}
      "master": "{{ $master }}",
      "mode": "{{ $mode }}",
      {{- end }}
      "ipam": {
        "type": "{{ $ipamType }}"
        {{- if and $network.subnet (ne $ipamType "static") }},
        "subnet": "{{ $network.subnet }}"
        {{- end }}
      }
    }
{{- end }}
