{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "free5gc-charging-portal.secretName" . }}
  labels:
    {{- include "free5gc-charging-portal.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.operatorPinKey }}: {{ .Values.auth.operatorPin | quote }}
  {{ .Values.auth.chfBearerTokenKey }}: {{ .Values.auth.chfBearerToken | quote }}
{{- end }}
